version: "3.10"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    environment:
      - FAST_API=app.py
      - API_PORT=8000
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: >
      bash -c "poetry install --no-root &&
               uvicorn app:app --host 0.0.0.0 --port 8000"